version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/staging.richmondsunlight.com/
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/staging.richmondsunlight.com/
    owner: ubuntu
    group: www-data
    mode: 755
    acls:
      - "u::rwx"
      - "g::rx"
      - "o::rx"
      - "d:u::rwx"
      - "d:g::rx"
      - "d:o::rx"
    type:
      - directory
  - object: /var/www/staging.richmondsunlight.com/
    owner: ubuntu
    group: www-data
    mode: 755
    acls:
      - "u::rwx"
      - "g::rx"
      - "o::rx"
    type:
      - file
hooks:
  BeforeInstall:
    - location: deploy/predeploy.sh
  AfterInstall:
    - location: deploy/postdeploy.sh
