---
version: 0
os: linux
files:
  - source: ./
    destination: /var/www/staging.richmondsunlight.com/
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/staging.richmondsunlight.com/
    owner: www-data
    group: www-data
    mode: 775
    type:
      - directory
hooks:
  BeforeInstall:
    - location: deploy/predeploy.sh
      timeout: 300
      runas: root
  Install: []
  AfterInstall:
    - location: deploy/postdeploy.sh
