version: '3.2'
services:
  web:
    build:
      context: deploy/
      dockerfile: Web.Dockerfile
    depends_on:
      - api
      - db
    ports:
      - "8000:80"
    volumes:
      - type: bind
        source: .
        target: /var/www
    container_name: rs_web
    networks:
      - rs_network
  api:
    build:
      context: api/deploy/
      dockerfile: API.Dockerfile
    depends_on:
      - db
    ports:
      - "5001:80"
    volumes:
      - type: bind
        source: ./api/htdocs/
        target: /var/www/html/
    container_name: rs_api
    networks:
      - rs_network
  db:
    build:
      context: api/deploy/
      dockerfile: MySQL.Dockerfile
    volumes:
      - db_data:/var/lib/mariadb
    restart: always
    ports:
      - "3306:3306"
    container_name: rs_db
    networks:
      - rs_network
  owasp_zap:
    build:
      context: deploy/
      dockerfile: ZAP.Dockerfile
    ports:
      - "5002:8080"
    container_name: rs_zap
    networks:
      - rs_network
volumes:
  db_data: {}
networks:
  rs_network:
    driver: bridge
