version: '3.2'
services:
  web:
    build:
      context: deploy/
      dockerfile: Web.Dockerfile
    links:
      - api:api
      - db:db
    ports:
      - "5000:80"
    volumes:
      - type: bind
        source: .
        target: /var/www
    container_name: rs_web
  api:
    build:
      context: api/deploy/
      dockerfile: API.Dockerfile
    links:
      - db:db
    ports:
      - "5001:80"
    volumes:
      - type: bind
        source: ./api/htdocs/
        target: /var/www/html/
    container_name: rs_api
  db:
    build:
      context: api/deploy/
      dockerfile: MySQL.Dockerfile
    volumes:
      - db_data:/var/lib/mariadb
    restart: always
    ports:
      - "3306:3306"
    container_name: rs_db
  owasp_zap:
    build:
      context: deploy/
      dockerfile: ZAP.Dockerfile
    ports:
      - "5002:8080"
    container_name: rs_zap
volumes:
    db_data: {}
