version: '3.8'
services:
  # Primary web interface
  web:
    build:
      context: deploy/
      dockerfile: Web.Dockerfile
    depends_on:
      api:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "8000:80"
    volumes:
      - type: bind
        source: .
        target: /var/www
    container_name: rs_web
    networks:
      - rs_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      start_period: 30s
      interval: 15s
      timeout: 5s
      retries: 3

  # API service
  api:
    build:
      context: api/deploy/
      dockerfile: API.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:80"
    volumes:
      - type: bind
        source: ./api/htdocs/
        target: /var/www/html/
    container_name: rs_api
    networks:
      - rs_network
    healthcheck:
      test: ["CMD", "apache2ctl", "-M"]
      start_period: 30s
      interval: 15s
      timeout: 5s
      retries: 3

  # Database
  db:
    build:
      context: api/deploy/
      dockerfile: MySQL.Dockerfile
    volumes:
      - db_data:/var/lib/mariadb
    restart: always
    ports:
      - "3306:3306"
    container_name: rs_db
    networks:
      - rs_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      start_period: 30s
      interval: 15s
      timeout: 5s
      retries: 3

  # Security testing service
  owasp_zap:
    build:
      context: deploy/
      dockerfile: ZAP.Dockerfile
    ports:
      - "5002:8080"
    container_name: rs_zap
    networks:
      - rs_network

volumes:
  db_data: {}
networks:
  rs_network:
    driver: bridge
